name: fr_notify
description: Flutter Rapid Notify (fr_notify)
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fr_core:
    path: ../fr_core

  fr_ui:
    path: ../fr_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
